### ISSUE TITLE
Update to Node.js 20

### ISSUE THREAD

**Issue by JPowell-AA** [ScaCap/action-surefire-report#202]
Getting build warning:
"_Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: scacap/action-surefire-report@v1._"

For more information see: 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by ghaiszaher** [comment]
Thanks @JPowell-AA. It is planned to upgrade to Node 20 soon with https://github.com/ScaCap/action-surefire-report/pull/185 - as soon as https://github.com/nock/nock/issues/2397 is solved which appears to be soon.

I'll wait for a few days until the fix is released, if it takes too long I'll disable the tests and merge the PR.

**Comment by mbazos** [comment]
Hey @ghaiszaher  update on this? Should you maybe disable the tests and merge the PR?

**Comment by ghaiszaher** [comment]
@mbazos I am raising the pull request now, hopefully released by tomorrow

**Comment by ghaiszaher** [comment]
Upgrade to Node 20 was released, please make sure to use tags `v1.8.0` or `v1`
